language: rust

cache:
  - cargo

rust:
  - 1.31.0
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
    - libasound2-dev
    - libsdl2-dev

install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      && brew install sdl2;
    fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" && "${TRAVIS_RUST_VERSION}" == "1.31.0" ]; then
      (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
      && (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.1" mdbook)
      && cargo install-update -a;
    fi

script:
  - cargo test --verbose
  - if [ "${TRAVIS_OS_NAME}" == "linux" && "${TRAVIS_RUST_VERSION}" == "1.31.0" ]; then
      mdbook build;
    fi

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: book
  keep-history: false
  fqdn: tetra.seventeencups.net
  on:
    branch: master
    condition: $TRAVIS_OS_NAME == "linux" && $TRAVIS_RUST_VERSION == "1.31.0"
